# ===============================
# 基本设置
# ===============================
project:
  name: CLAP-HMM
  seed: 42
  device: cuda

# ===============================
# 数据配置
# ===============================
data:
  dataset_name: Populus_alba_resistance
  train_data: data/train.fasta
  val_data: data/val.fasta
  test_data: data/test.fasta
  label_file: data/labels.csv
  batch_size: 32
  num_workers: 4
  max_seq_len: 2000

# ===============================
# 模型配置
# ===============================
model:
  name: CNNLSTM_GatedFusion
  input_dim: 4             # A/C/G/T one-hot 编码
  cnn_channels: 64
  kernel_size: 7
  lstm_hidden: 128
  lstm_layers: 1
  attention_dim: 128
  use_attention: true

  # ProtHint辅助特征
  aux_dim: 2               # ProtHint输出维度
  fusion: gated            # 可选: gated / concat / attention
  fusion_output_dim: 130   # 最终融合后维度

# ===============================
# 优化器 & 学习率策略
# ===============================
optimizer:
  type: Adam
  lr: 0.001
  weight_decay: 1e-5
  scheduler: cosine
  warmup_epochs: 5

# ===============================
# 训练设置
# ===============================
training:
  epochs: 100
  save_dir: outputs/
  log_interval: 10
  save_interval: 5
  early_stopping: true
  patience: 10

# ===============================
# 测试 & 推理
# ===============================
inference:
  output_file: outputs/predictions.csv
  threshold: 0.5

# ===============================
# 日志与可视化
# ===============================
logging:
  use_wandb: false
  log_dir: logs/
  plot_attention: true
